services:
  mysql:
    image: mysql:latest
    container_name: mysql_livrosdb  
    ports:
      - 3306:3306
      
    environment:
      - MYSQL_ROOT_PASSWORD=senhasegura
    networks:
      - webnet
    volumes:
      - volume_mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_livrosdb  
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=senhasegura
    networks:
      - webnet
    depends_on:
      - mysql

  backend:
    container_name: backendlivros
    build: ./backend
    ports:
      - 4444:4444
    env_file:
      - ./backend/.env
    networks:
      - webnet
    volumes:
      - volume_logs:/app/log
    depends_on:
      - mysql

  frontend:
    container_name: frontendlivros
    build: ./frontend
    ports:
      - 8000:80
    env_file:
      - ./frontend/.env
    networks:
      - webnet
    depends_on:
      - backend

networks:
  webnet:
    driver: bridge

volumes:
  volume_mysql:
  volume_logs:
