# Usar a imagem base do Ubuntu
FROM ubuntu:latest

# Instalar o Nginx
RUN apt-get update && apt-get install -y nginx

# Expor a porta 7000
EXPOSE 7000

# Copiar arquivos de configuração do Nginx, se necessário
# COPY ./nginx.conf /etc/nginx/nginx.conf

# Iniciar o servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
