# Usa a imagem base do Node.js
FROM node:14

# Cria um diretório de trabalho para o back-end
WORKDIR /app

# Copia o arquivo back.js para o diretório de trabalho do contêiner
COPY back.js .

# Inicializa o npm e instala as dependências (caso necessário)
RUN npm init -y

# Expõe a porta 4000 para o contêiner
EXPOSE 4000

# Comando para rodar o back.js
CMD ["node", "back.js"]
