-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 00:30:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lojaweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lojaweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lojaweb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lojaweb` ;

-- -----------------------------------------------------
-- Table `lojaweb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaweb`.`categorias` (
  `IDCategoria` INT NOT NULL AUTO_INCREMENT,
  `descricao_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IDCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lojaweb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaweb`.`clientes` (
  `IDCliente` INT NOT NULL AUTO_INCREMENT,
  `CPF_cliente` VARCHAR(11) NOT NULL,
  `nomeCompleto_cliente` VARCHAR(100) NOT NULL,
  `NCelular_cliente` VARCHAR(15) NOT NULL,
  `email_cliente` VARCHAR(100) NOT NULL,
  `dataNascimento_cliente` DATE NOT NULL,
  `Enderecos_cliente` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IDCliente`),
  UNIQUE INDEX `CPF_cliente` (`CPF_cliente` ASC) VISIBLE,
  UNIQUE INDEX `email_cliente` (`email_cliente` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lojaweb`.`formapagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaweb`.`formapagamento` (
  `IDPagamento` INT NOT NULL AUTO_INCREMENT,
  `formasPagamento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IDPagamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lojaweb`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaweb`.`compras` (
  `IDCompras` INT NOT NULL AUTO_INCREMENT,
  `enderecoEnvio_compra` TEXT NOT NULL,
  `descontoAplicado` DECIMAL(5,2) NULL DEFAULT '0.00',
  `total_compra` DECIMAL(10,2) NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `IDCliente` INT NULL DEFAULT NULL,
  `IDPagamento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDCompras`),
  INDEX `IDCliente` (`IDCliente` ASC) VISIBLE,
  INDEX `IDPagamento` (`IDPagamento` ASC) VISIBLE,
  CONSTRAINT `compras_ibfk_1`
    FOREIGN KEY (`IDCliente`)
    REFERENCES `lojaweb`.`clientes` (`IDCliente`),
  CONSTRAINT `compras_ibfk_2`
    FOREIGN KEY (`IDPagamento`)
    REFERENCES `lojaweb`.`formapagamento` (`IDPagamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lojaweb`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaweb`.`subcategorias` (
  `IDSubcategoria` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `IDCategoria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDSubcategoria`),
  INDEX `IDCategoria` (`IDCategoria` ASC) VISIBLE,
  CONSTRAINT `subcategorias_ibfk_1`
    FOREIGN KEY (`IDCategoria`)
    REFERENCES `lojaweb`.`categorias` (`IDCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lojaweb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaweb`.`produtos` (
  `IDProduto` INT NOT NULL AUTO_INCREMENT,
  `modelo_produto` VARCHAR(100) NOT NULL,
  `fabricante_produto` VARCHAR(100) NOT NULL,
  `preco_produto` DECIMAL(10,2) NOT NULL,
  `qtdDisponivel_produto` INT NOT NULL,
  `IDSubcategoria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDProduto`),
  INDEX `IDSubcategoria` (`IDSubcategoria` ASC) VISIBLE,
  CONSTRAINT `produtos_ibfk_1`
    FOREIGN KEY (`IDSubcategoria`)
    REFERENCES `lojaweb`.`subcategorias` (`IDSubcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lojaweb`.`itemcompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaweb`.`itemcompra` (
  `IDItemCompra` INT NOT NULL AUTO_INCREMENT,
  `IDCompras` INT NULL DEFAULT NULL,
  `IDProduto` INT NULL DEFAULT NULL,
  `precoUnitario` DECIMAL(10,2) NOT NULL,
  `qtd_itemCompra` INT NOT NULL,
  `NSerie` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`IDItemCompra`),
  INDEX `IDCompras` (`IDCompras` ASC) VISIBLE,
  INDEX `IDProduto` (`IDProduto` ASC) VISIBLE,
  CONSTRAINT `itemcompra_ibfk_1`
    FOREIGN KEY (`IDCompras`)
    REFERENCES `lojaweb`.`compras` (`IDCompras`),
  CONSTRAINT `itemcompra_ibfk_2`
    FOREIGN KEY (`IDProduto`)
    REFERENCES `lojaweb`.`produtos` (`IDProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
