FROM ubuntu:latest


RUN apt-get update && apt-get install -y nginx


EXPOSE 7000


 COPY index.html /var/www/html/


RUN echo 'server { listen 7000; server_name localhost; location / { root /var/www/html; index index.html; } }' > /etc/nginx/sites-available/default


CMD ["nginx", "-g", "daemon off;"]
