services:
  backend:
    container_name: backend_expapi
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: bash -c "npx prisma migrate dev && npm run start"
  
  db:
    container_name: db_expapi
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    container_name: db_expapi_gui
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3308  # Atualizado para a nova porta
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - db

volumes:
  mysql_data:
  mysql_config:
